### ISSUE TITLE
Testafsnit

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#106]

**Comment by phil2988** [comment]
Der var skrevet en god del til punktet inden jeg gik i gang med det, så kan ikke komme med et tidsestimat. Jeg har skrevet Accepttest afsnittet, jeg ved ikke hvem der har lavet resten, men kan godt rette det

**Comment by HackTheOxidation** [comment]
Review tilføjet til afsnit om "Accepttest".
