### ISSUE TITLE
Privat profilvisning

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#68]

**Comment by phil2988** [comment]
Venter på at der er lavet en generel skitse af systemet, da det skal fastlægges hvad forskellen mellem privat og offenlig profil er

**Comment by phil2988** [comment]
Fungerer, bruger 6 tomme template wearable posts som standard

**Comment by phil2988** [comment]
Man kan nu gå ind på sin profil, hvor den viser et billede og beskrivelse af éns profil samt wearables i databasen der er knyttet til brugeren.
Hvis der mangler billeder/wearables eller der er fejl vil det også blive håndteret

**Comment by Omarley7** [comment]
Ser pisse godt ud! Mangler dog at hente billeder fra storage account.
Jeg har påbegyndt en implementering i klassen AzureImageStorage klassen. For at oprette en instans skal du bruge følgende connection string:
"DefaultEndpointsProtocol=https;AccountName=wearhouseimages;AccountKey=XsPSwlsWqpM67glYBUVc/d5Tm5XBKx3KTgZg3dCo6Hz2rHnz9+mQH3cmgnSLJsRK6gmDtOPEj0y0860AhGgWBw==;EndpointSuffix=core.windows.net"

Dokumentation af hvordan Azure Blob Storage virker findes her:
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet#create-a-container

**Comment by SigurdSkov** [comment]
Jeg ønsker gerne at hvis der tilføjes en beskrivelse af brugeren, bør denne være koblet op til serveren. Ellers burde den ikke være der, da alles beskrivelse vil være identiske.

**Comment by Omarley7** [comment]
Godkendt, virker med billeder og det hele.
