### ISSUE TITLE
Kontakt

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#70]

**Comment by SigurdSkov** [comment]
En time brug på at beskrive løsningsmetoder

**Comment by SigurdSkov** [comment]
Brugere kan skrive og læse kommentarer på egne og andres Wearableposts.
Kommentarerne persisterer igennem alle computere

**Comment by skragh** [comment]
Implementeret at brugere kan læse og skrive kommentarer: 
Søren brugt 5-6 timer, sigrud brugt xx timer.
