### ISSUE TITLE
Genlaves domænemodel

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#72]

**Comment by phil2988** [comment]
Første iteration... Tog 30 min.

**Comment by skragh** [comment]
Arbejdet lidt videre på domænemodellen og lavet en V3
![image.png](https://images.zenhubusercontent.com/61433b244cc76eba14da3540/eac8b6fc-ee0e-44bf-908b-f8c3d3eea81f)
