### ISSUE TITLE
Fremtidig implementation

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#82]

**Comment by HackTheOxidation** [comment]
Afsnit: "Fremtidigt Arbejde" er indskrevet i rapporten.

**Comment by Omarley7** [comment]
Ganske fint afsnit. Elsker overvejeslerne der bliver lavet i henhenhold til krav. Kan vi få lidt mere af det? Evt. en roadmap af hvilke ting vi gerne vil implementere i hvilke verisoner eg. version 1.1 => Nu kan man redigere opslag og profiler i henhold til Should krav nr. 1,2 og 3. Samt  Prioritetet vising af adresse ting.
Version 1.2 => Implentering af søge/filter funktion
Forslag:

     Privat chat
    
    Betalingssystem implementeret
    
    App
    Notifikation
    
    Scout funktionalitet


Bund og grund, bare lidt mere reference til de orginale krav og måske hvorfor det er vigtigt det bliver lavet i den rækkefølge.

**Comment by HackTheOxidation** [comment]
Fremtidigt arbejde er blevet "refactored" med Omar's kommentar.
