### ISSUE TITLE
Arkitekturafsnit

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#83]

**Comment by skragh** [comment]
3 timer brugt: Skrevet/tilføjet domænemodel. Skrevet om C4 model + opsat struktur.
Mangler C4 model, der passer præcis til vores design (skal bruge lidt hjælp).

**Comment by skragh** [comment]
2.5 time: Redigeret C4 til at stemme overens med nuværende arkitektur, visio dokument lagt på drev. Skrevet afsnit om Contekts, Container og Component i Arkitektur afsnit.
Mangler: Sekvens diagrammer for Container og Component diagram (1-2 timer)
Beskrivelse af database og persistering med ERD og yderligere beskrivelse af repository pattern (2 timer)

**Comment by skragh** [comment]
1 time: Sekvensdiagrammer for Container og Component diagram skrevet

**Comment by SigurdSkov** [comment]
Review
Jeg ønsker hellere til domænemodellens figurtekst kortes lidt ned, til fordel for at liste alle taleemnerne som underpunkter. Paragraffen er i øjeblikket en meget solid blok af tekst der kan være svær at gennemskue og få overblik over.
Sætning ønsker omformuleret på side
Billede på side 22 ikke indlæst
Lagring af data ikke beskrevet
C4 model mangler laveste beskrivelse (klassediagram lite)

**Comment by Omarley7** [comment]
Har tilføjet en del kommentar ned igennem overleaf. Især domæne modellen, synes jeg trænger til en overhaling. Der er nogle uheldige formuleringer, som ikke bliver grebet i resten af rapporten, hvilket gør det en anelse sværer at læse. Har kommenteret en del forslag til dette afsnit.

Jeg har næsten færdigskrevet nogle lidt større ændringer til komponent afsnittet, da det ligger meget op ad repo pattern. 
Tænker det er her det giver god mening at introducere behovet for adskillelse af lag (entitet og forretning).

Lagring af data
Her giver det rigtig god mening at introducere de forskellige modeller's ansvars områder. er igang med en skrivsel.
Der er mange ting, der er blevet gentaget tidligere i rapport, som snakker om hvordan ting bliver gemt på en database. Det bør slettes, for ellers er det her afsnit overflødigt. 

Giver en rigtig god overgang til at præsentere nogle klassediagram som indledning til Design og Implementering.
