### ISSUE TITLE
Analysearbejde

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#85]

**Comment by SigurdSkov** [comment]
Definition of Done
Teknologianalyse, risikoanalyse
Hvad man har fundet frem til
Grundllæggende valg af platforme osv.

**Comment by HackTheOxidation** [comment]
Definition of Done (DoD): Der er indskrevet et afsnit i Rapporten om 
'Analyse' i overensstemmelse med retningslinjerne angivet i "Vejledning til udfærdigelse af Projektrapporter".

**Comment by skragh** [comment]
Elementet er oprettet og skrevet. Der er enkelte rettelser i forhold til at skabe en rød tråd og mindre elementer, der godt kunne indlemmes i analysen. Dette er beskrevet med kommentarer i latex

Risikoanalyse udeladt, der mangler en reel risikoanalyse i rapporten.
