### ISSUE TITLE
Gennemlæs rapport og sørg for rød tråd

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#95]

**Comment by SigurdSkov** [comment]
Der skal skrives kommentarer hvor relevant

**Comment by skragh** [comment]
Der er lavet kommentarer under hvert afsnit, som gør opmærksom på problemstillinger/elementer der mangler/skal skrives om, for at en rød tråd er indeholdt i rapporten.

Nogle punkter er medtaget til dagsorden for gruppemødet.
