### ISSUE TITLE
Dokumentation for kode

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#96]

**Comment by SigurdSkov** [comment]
XML Dokumentation - påbegyndt, dvs Der undersøges hvordan dokumentation kan skrives i kildekode og eksporteres, samt arbejde påbegyndt.

**Comment by phil2988** [comment]
Som jeg husker det, så indebærer dette at der skal laves dokumentation i form af kommentarer i koden hvor brugbart. Hovedsageligt ved brug af ///
