### ISSUE TITLE
Procesrapport udkast

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#97]

**Comment by SigurdSkov** [comment]
Jeppe
GIT strategi beskrives
SCRUM strategi beskrives
Risikoanalyse
Hvordan har den ændret sig, hvad var den før, hvorfor ændrede den sig, hvad er den nu?

**Comment by SigurdSkov** [comment]
2 timer skrevet på projektrapport
Rapport opsat

**Comment by SigurdSkov** [comment]
2 timer skrevet på projektrapporten

**Comment by SigurdSkov** [comment]
2 timer skrevet på projektrapporten, nu færdigskrevet udkast

**Comment by phil2988** [comment]
Ikke flere udkast xD
