### ISSUE TITLE
Finpudsning

### ISSUE THREAD

**Issue by SigurdSkov** [PRJ4WearHouse/Project#98]

**Comment by SigurdSkov** [comment]
state typer kan vælges for en wearable ved create og knappen ved edit profile giver ikke en fejlside

**Comment by skragh** [comment]
Edit knap ved profile (når man er logget ind) giver stadig fejl -> mangler fiks

Adskillige kommentarer af gammel kode er ikke fjernet (blandt andet i controllere)

Der kan sættes setting på wearable, men denne setting (sell/rent/loan etc) bliver ikke brugt nogen steder og kan ikke ændres efter oprettelse.

Efter oprettelse af wearable fås: ![image.png](https://images.zenhubusercontent.com/61433b244cc76eba14da3540/155bf9f8-d1f2-4494-9ae7-532f03b8fab8)

kunne fikses
